name: Jobs Scraper

on:
  schedule:
    - cron: '3 8 * * 0'  # každou středu? v 8:00 UTC
  workflow_dispatch:      # umožňuje ruční spuštění

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      run: my_job_v02.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: scraped-jobs
        path: nabidky_prace/
