jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      run: python my_job_v02.py

    - name: Commit and push results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add nabidky_prace/
        git commit -m "Automaticky uložené výsledky scrapu [skip ci]" || echo "No changes to commit"
        git push

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: scraped-jobs
        path: nabidky_prace/
