on:
  schedule:
    - cron: '0 10 * * 3'   # každou středu v 10:00 UTC (středa: 3)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      run: python my_job_v02.py

    - name: Upload results to FTP
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          localDir: nabidky_prace/
          remoteDir: /www/Projekt_DP_4/



    - name: Upload results as GitHub artifact
      uses: actions/upload-artifact@v4
      with:
        name: scraped-jobs
        path: nabidky_prace/

